### ISSUE TITLE
Words remain visible after they are chosen

### ISSUE THREAD

**Issue by ryabroscoe** [benjamintd/codenames.cards#26]
Can you hide or gray out the words after they have been chosen? In the physical game, the word gets covered up and can therefore be used as a clue (as it is no longer visible). For this version, it’s a bit confusing since a chosen word still looks like an available word. Thanks!

**Comment by benjamintd** [comment]
Hi @ryabroscoe, you're right, we're working with @msmorgan to implement this. 

Perhaps it would be a good idea to implement add an option for this so that people can still play with the current version of the game?
