### ISSUE TITLE
Duet turn counter wrong

### ISSUE THREAD

**Issue by brewerja** [benjamintd/codenames.cards#32]
The number of turns remaining decreases upon giving a clue AND when missing on a guess. This is double counting. You should have 9 turns: Give a clue and miss guess is only one turn.

Also, I'm noticing that I have to refresh the page in some cases to get it to update what the other player is already seeing for turns remaining.

**Comment by benjamintd** [comment]
Hi @brewerja. 
Here's a snippet from the Duet rules in English. I understood that it means one turn is consumed by clicking on a wrong card: 

> If your partner touches a word you see as tan, mark it with a timer token. Take a token from the time bank and place it on the word card, bystander side up, with the arrow pointing from you to your partner. This indicates that when you gave a clue, your partner guessed this word and ran
into an innocent bystander. Do not cover the word. This still might be a word that your partner wants you to guess.

Source: https://czechgames.com/files/rules/codenames-duet-rules-en.pdf

I agree we should add some more options to the duet game, for instance to play with more time tokens or configure when they are consumed. However I believe the original rules intend to consume a turn when making a wrong guess.

**Comment by brewerja** [comment]
Yeah, so in the game, there are 9 timer tokens. When you miss a guess, you take a timer token and place it on the miss. However, if you don't miss and decide to end your turn, you also take a timer token.

You don't take timer tokens upon giving the clue.

Right now, you have it decrementing the turn counter both on the giving of a clue and on missing a guess.

When you run out of timer tokens, you enter "sudden death" and are allowed to guess until you miss to try and win.

**Comment by brewerja** [comment]
Applicable snippet:

> Each turn has exactly one clue and at least one guess. Assuming you don't run into an assassin,
there are two ways a turn can end:
• A wrong guess ends the turn. If your partner touches an innocent bystander, you mark it with a timer token from the time bank and the turn ends.
• After one or more correct guesses, your partner may choose to end the turn by taking a timer token from the time bank.
The token is kept checkmark side up in front of your partner.
A turn always uses up a timer token. The number of timer tokens left in the time bank is the number of turns (and the number of clues) left in the game.
If everything goes well, your partner will guess as many words as you indicated by your clue
and then stop. But your partner may choose to quit early. It is also legal for your partner to take additional wild guesses, but we don't recommend it .

**Comment by benjamintd** [comment]
Oh I understand. My mistake, you're right! I only ever played the physical version of the classic game, not the duet one, which is why I misunderstood the rules.

I'll open a PR for that this weekend, unless you want to take a stab at it?

**Comment by brewerja** [comment]
I'm not a JS dev, so I'm pretty ignorant when it comes to npm/yarn/webpack/React. So I'll let you handle it. I tried running locally but ran into some issues.

Your solution seems fair if you don't have passing.
