### ISSUE TITLE
Firebase instructions for new contributors

### ISSUE THREAD

**Issue by oriain** [benjamintd/codenames.cards#48]
It would be helpful to add some instructions for the Firebase dependency.  I played this with friends for the first time today and was interested in contributing, but I'm new to Firebase; I created a new project (and database), but it's a little hard to know what values to put in the `.env` file, and from where in Firebase UI to grab them.

**Comment by benjamintd** [comment]
Hi @oriain, good idea!
I have posted very basic instructions to master. Let me know if that's enough for you to get started - don't hesitate to take screenshots in the process so we can complete the readme if needed! That would be a very helpful first contribution.

If the instructions are unclear let me know which part need more explanation and I'll try to make it clearer.

**Comment by benjamintd** [comment]
If that answered your questions, I'll close this issue. Feel free to reopen or suggest changes if the current instructions are not enough to get started easily!

**Comment by oriain** [comment]
Thank you adding additional instructions. I haven't had a chance to come back to this, but I look forward to contributing when I have some more free time. Cheers!
